cmake_minimum_required(VERSION 3.8)
project(agt_map_runner)
find_package(ament_cmake REQUIRED)
install(PROGRAMS scripts/map_runner.py DESTINATION lib/${PROJECT_NAME} RENAME map_runner)
if(BUILD_TESTING)
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  add_test(NAME test_map_runner COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/test/test_map_runner.py)
endif()
ament_package()
